FROM centos

RUN rpm -Uvh http://li.nux.ro/download/nux/dextop/el7/x86_64/nux-dextop-release-0-1.el7.nux.noarch.rpm

RUN yum -y update && yum -y install vlc

RUN adduser vlc

USER vlc

WORKDIR /home/vlc

CMD /usr/bin/vlc -v -I dummy --run-time=60 --sout "#file{mux=mp4,dst=out.mp4,access=file}" ${STREAM_URL} vlc://quit
